feat(SignUp): dbとの連携処理の追加
GCXHam/dev-daemon pull request #30
Opened 2021-11-09 14:57 UTC by Yuki992411

サインアップ時にdbにアカウント情報を保存する #24 
* authのuid
* userの名前
* iconURL
* timestamp

2021-11-09 15:11 UTC, Yuki992411 commented
firebaseのドキュメントに保存するにあたって，

- `authのuid`がドキュメントのname
- 以下，そのデータ
  - userの名前(表示名)
  - iconURL
  - timestamp

となってますが．離席確認情報はどのように保存しますか？あと，他何か保存すべきものはありますか？

2021-11-09 18:01 UTC, TetsuOtter commented
![Database](https://user-images.githubusercontent.com/31824852/140978562-24655cd9-ef55-4f7d-aca5-01bbf4241372.png)

離席確認情報は、teams/usrs/[uid]/stateに保存する形を取ります。

なので、とりあえずSignUp時点ではそれで十分だと思います

レビューは暫しお待ちを

2021-11-09 23:19 UTC, Yuki992411 commented
後の話になると思いますが、teams/usrs/[uid]/stateの型はBooleanにした方が、文字列のパースをする手間が省けそうです。

2021-11-11 07:11 UTC, TetsuOtter requested changes

2021-11-11 13:25 UTC, TetsuOtter commented
> 後の話になると思いますが、teams/usrs/[uid]/stateの型はBooleanにした方が、文字列のパースをする手間が省けそうです。

`IsActive`とかいう変数名にして「現在アクディブ = 連絡可能か否か」のデータのみを記録するのであればbooleanが適当ですが、将来性を考えると`type`で制約を付けたstringが適当かなと思ってstringにしてます

とりあえず`Working`と`Leaving`だけしか使用しないつもりですが、将来的に休憩中って`OnBreak`を追加することもできますし、よほどパフォーマンス制約が厳しくなければ文字列比較でも大丈夫だと思います

2021-11-13 11:21 UTC, Yuki992411 commented on src/SignUp.js
> +        const ctrler = new DevDaemonDBController(app);
>ctrlerインスタンスはCheckStatusページでも使用することになるため, これはアプリケーション全体で共有してあげた方がいいと思います.

了解です。`createContext`を使用しようと思います。

2021-11-13 11:26 UTC, Yuki992411 commented on src/SignUp.js
>          history.push("/checkstatus");
> createNewMasterUserData関数では「ユーザデータの作成」のみ行われるため, 次回以降同じctrlerインスタンスでDB操作を行う場合は毎度毎度UID指定が必要になりますので, ご注意ください.
ちなみに : ctrlerインスタンスにUIDをセットするには, setUserID関数を使用します

了解です！ただ、
> まぁctrlerインスタンスをグローバルで共有する

この方針で行なおうと考えています

2021-11-13 11:35 UTC, Yuki992411 commented
> > 後の話になると思いますが、teams/usrs/[uid]/stateの型はBooleanにした方が、文字列のパースをする手間が省けそうです。
> 
> `IsActive`とかいう変数名にして「現在アクディブ = 連絡可能か否か」のデータのみを記録するのであればbooleanが適当ですが、将来性を考えると`type`で制約を付けたstringが適当かなと思ってstringにしてます
> 
> とりあえず`Working`と`Leaving`だけしか使用しないつもりですが、将来的に休憩中って`OnBreak`を追加することもできますし、よほどパフォーマンス制約が厳しくなければ文字列比較でも大丈夫だと思います

了解しました！では、`string`で進めましょう！

2021-12-04 13:35 UTC, TetsuOtter approved these changes

2021-12-04 13:37 UTC, TetsuOtter commented
@Yuki992411 授業の都合で遅くなりましたが, Approveしました！

この実装で何か不都合があれば, おいおい変えていくということで

2021-12-04 14:59 UTC, merged