Impl for accessing db in login
GCXHam/dev-daemon pull request #37
Opened 2022-01-15 03:12 UTC by Yuki992411

以下，2つについてお聞きしたいです．
* useAuthContext内のteam_nameやuserの必要性（`db_ctrler`だけでいいかもしれない）
* 所属していないチーム名が入力されたときの動作

今回は，setTeamIDメソッドは未完成？（←TODOが残っていた）と思い，team_nameを任意のコンポーネント間で使用できるようにしました．

他にもコードの書き方的におかしい点（typescriptだとこんな書き方しないなぁとか）あったらなんでも指摘お願いします！

2022-01-15 03:20 UTC, TetsuOtter commented on src/pages/Login.tsx
> +  /** TODO:
`/** hogehoge */`というように, ブロックコメントの開始時にアスタリスクを2つ連ねるのは, それがJSDoc向けコメントであることを示すためです.
なので, 通常のブロックコメントであれば`/* hogehoge */`のような形で構いません

2022-01-15 03:34 UTC, TetsuOtter requested changes

2022-01-15 03:34 UTC, TetsuOtter commented on src/pages/Login.tsx
> +      /** TODO:
`/** hogehoge */`というように, ブロックコメントの開始時にアスタリスクを2つ連ねるのは, それがJSDoc向けコメントであることを示すためです.
なので, 通常のブロックコメントであれば`/* hogehoge */`のような形で構いません

2022-01-15 03:34 UTC, TetsuOtter commented on src/pages/Login.tsx
> +      db_ctrler = new DevDaemonDBController(app);
JavaScriptにあまり詳しくないので間違っていたら申し訳ないんですが, この書き方だとローカル変数としての`db_ctrler`に代入していて, `AuthContext`側の`db_ctrler`には値が代入されないのではないかと思います.

また, `db_ctrler`がundefinedでない場合 (=インスタンスを再生成する必要がない場合) にもインスタンスの生成を行ってしまっているため, NULLチェックやNULL合体代入演算子を使う等で, 不要なインスタンス生成はさけたほうが良さそうに思います. (まぁパフォーマンス的な問題だけなはずなので, 別に気にしなくても大丈夫といえば大丈夫ですが)

2022-01-15 03:43 UTC, TetsuOtter commented
> useAuthContext内のteam_nameやuserの必要性（db_ctrlerだけでいいかもしれない）

db_ctrlerから両者とも参照可能なので, `AuthContext`側で保持しなくても大丈夫です！

---

> 所属していないチーム名が入力されたときの動作

その場合はエラーを出力で大丈夫だと思います.  一応, 管理者(チームリーダー)がメンバーを追加することを想定しています.  join requestとかの機能は面倒なのでenhancementで…

---

> 今回は，setTeamIDメソッドは未完成？（←TODOが残っていた）と思い，team_nameを任意のコンポーネント間で使用できるようにしました．

TODO…完全に忘れてました…  とりあえず, そのTODOは「チームにユーザが本当に登録されているか」をチェックするだけなので, DB内でデータ齟齬が発生していない限りそのまま使っても問題ないです👍

2022-01-15 13:08 UTC, Yuki992411 commented on src/pages/Login.tsx
> +  /** TODO:
なるほど！
C++のソースコードでもときどき見かけていましたが、、、

勉強になります。

では、コメントアウトは、シンプルにvscodeのショートカットキーにお任せする形にします。
一行も複数行も`//`になるかなと。

2022-01-15 13:47 UTC, Yuki992411 commented on src/pages/Login.tsx
> +      db_ctrler = new DevDaemonDBController(app);
> JavaScriptにあまり詳しくないので間違っていたら申し訳ないんですが, この書き方だとローカル変数としてのdb_ctrlerに代入していて, AuthContext側のdb_ctrlerには値が代入されないのではないかと思います.

そうですね．．実際に確認してみました．`undefined`です．

---
>また, db_ctrlerがundefinedでない場合 (=インスタンスを再生成する必要がない場合) にもインスタンスの生成を行ってしまっているため, NULLチェックやNULL合体代入演算子を使う等で, 不要なインスタンス生成はさけたほうが良さそうに思います.

ただ，`Login.tsx`のサインイン成功時やサインアップ時の処理なら，新しくユーザーが変わることで，それまでのプロパティの状態は初期化する必要があるため，インスタンスを再生成する必要があるのではないのでしょうか？

2022-01-15 13:50 UTC, Yuki992411 commented
`AuthContext`のuserを保持する件は，`SignUp.tsx`も関係するので，別のPRで改修します．

2022-01-16 06:01 UTC, TetsuOtter commented on src/pages/Login.tsx
> +      db_ctrler = new DevDaemonDBController(app);
確かに、サインアウト時にインスタンス再生成が一番楽そうです
ただ、その辺はAuthContext側でサインイン状態の監視をする事でインスタンスの破棄/生成をする形が自然そうな気がします。

ただ、この修正はこのPRのテーマから外れてしまう気がするので、別で修正しましょう！

2022-01-16 06:20 UTC, Yuki992411 commented
@TetsuOtter 

再度，修正しました．
* コメントの記述スタイル
* `db_ctrler`を任意のコンポーネントで共有可能
* `team_name`を`db_ctrler`内で保持
* サインイン失敗時にサインアウトするように変更
　* `db_ctrler`でエラーハンドリングしても，サインイン情報が残ったままであったため．

ただ，リロードすると，`db_ctrler`の情報が消えてしまいます．．．
これへの対処として，`Indexed DB`を用いる必要があるかもしれません．
(uesr情報はfirebaseが`Indexed DB`に保存していました)

確認，おねがいします！

2022-01-16 06:22 UTC, TetsuOtter approved these changes

2022-01-16 06:23 UTC, TetsuOtter commented
大丈夫そうです!
リロード時にインスタンスが消えるのは、別でIssueを建てて対応しましょう!

2022-01-16 06:33 UTC, merged